### ISSUE TITLE
TeeLogger without arguments

### ISSUE THREAD

**Issue by osteenbergen** [spriteCloud/teelogger#2]
Can't use the teelogger as a normal logger

```
irb(main):001:0> require "teelogger"
=> true

irb(main):002:0> t = TeeLogger::TeeLogger.new()
A, [2015-02-06T13:10:22.075745 #8488]   ANY -- : Logging to #<IO:0x00000000e89bf8> initialized with level .
=> #<TeeLogger::TeeLogger:0x000000010885a8 @loggers={"#<IO:0x00000000e89bf8>"=>#<Logger:0x000000010881e8 @progname=nil, @level=nil, @default_formatter=#<Logger::Formatter:0x00000001088148 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000001088058 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x0000000107fed0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000000107fd90>>>>}>

irb(main):003:0> t.debug "test"
ArgumentError: comparison of Fixnum with nil failed
    from /usr/lib/ruby/2.1.0/logger.rb:366:in `<'
    from /usr/lib/ruby/2.1.0/logger.rb:366:in `add'
    from /usr/lib/ruby/2.1.0/logger.rb:400:in `debug'
    from /var/lib/gems/2.1.0/gems/teelogger-0.2.0/lib/teelogger.rb:205:in `block in dispatch'
    from /var/lib/gems/2.1.0/gems/teelogger-0.2.0/lib/teelogger.rb:202:in `each'
    from /var/lib/gems/2.1.0/gems/teelogger-0.2.0/lib/teelogger.rb:202:in `dispatch'
    from /var/lib/gems/2.1.0/gems/teelogger-0.2.0/lib/teelogger.rb:148:in `block (2 levels) in <class:TeeLogger>'
    from (irb):4
    from /usr/bin/irb:11:in `<main>'
```

**Comment by osteenbergen** [comment]
Also the following line is missing the default level
"ANY -- : Logging to #IO:0x00000000e89bf8 initialized with level ."

**Comment by ghost** [comment]
Will fix ASAP.

**Comment by ghost** [comment]
Turned out to be a case of bad initialization with the default value. Fix is imminent.
